[viewer]
    Title = "hex-Go语言博客"
    Description = "hxw-Go语言博客"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/89962381"
    Zhihu = "https://www.zhihu.com/people/aw-zhi-lu"
    Avatar = "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Finews.gtimg.com%2Fnewsapp_bt%2F0%2F13147603927%2F1000.jpg&refer=http%3A%2F%2Finews.gtimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1647242040&t=c6108010ed46b4acebe18955acdd2d24"
    UserName = "工具人"
    UserDesc = "大帅比"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "替换自己的"
    QiniuSecretKey = "替换自己的"
    Valine = true
    ValineAppid = "xgKkleCRI3PAbLPHFfqOPQTY-9Nh9j0Va"
    ValineAppkey = "Xoj0zz5Y9StTrer4QFnf2eSh"
    ValineServerURL = "https://xgkklecr.lc-cn-e1-shared.com"